// このファイルは gen_master.js が temples_master.csv から自動生成します。直接編集しないでください。
window.TEMPLE_DATA = [
 {
  "no": "1",
  "name": "正暦寺",
  "kana": "",
  "area": "綾部",
  "addr": "寺町堂ノ前45",
  "lat": 35.292149,
  "lng": 135.262579,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "2",
  "name": "隆興寺",
  "kana": "",
  "area": "綾部",
  "addr": "神宮寺町上藤山2-1",
  "lat": 35.295144,
  "lng": 135.2561,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "3",
  "name": "宝住寺",
  "kana": "",
  "area": "綾部",
  "addr": "味方町井上寺48",
  "lat": 35.292843,
  "lng": 135.269877,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "4",
  "name": "栴林寺",
  "kana": "",
  "area": "中筋・山家",
  "addr": "釜輪町下尾道ノ上",
  "lat": 35.294019,
  "lng": 135.331692,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "5",
  "name": "照福寺",
  "kana": "",
  "area": "中筋・山家",
  "addr": "鷹栖町小丸山33",
  "lat": 35.296513,
  "lng": 135.314301,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "6",
  "name": "梅岩寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "下八田町水崎26",
  "lat": 35.309649,
  "lng": 135.280317,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "7",
  "name": "佛南寺",
  "kana": "",
  "area": "綾部",
  "addr": "里町向屋敷103",
  "lat": 35.315262,
  "lng": 135.258926,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "8",
  "name": "圓照寺",
  "kana": "",
  "area": "綾部",
  "addr": "多田町後路55",
  "lat": 35.321823,
  "lng": 135.268234,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "9",
  "name": "東光院",
  "kana": "",
  "area": "中筋・山家",
  "addr": "上延町堂ノ奥7",
  "lat": 35.295414,
  "lng": 135.229828,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "10",
  "name": "慈音寺",
  "kana": "",
  "area": "中筋・山家",
  "addr": "上延町新庄15",
  "lat": 35.299454,
  "lng": 135.232066,
  "approx": false,
  "sect": "曹洞宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "11",
  "name": "隠龍寺",
  "kana": "",
  "area": "中筋・山家",
  "addr": "高津町段30",
  "lat": 35.29871,
  "lng": 135.20842,
  "approx": false,
  "sect": "",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "12",
  "name": "浄泉寺",
  "kana": "",
  "area": "豊里東",
  "addr": "位田町田岸63",
  "lat": 35.314053,
  "lng": 135.248932,
  "approx": false,
  "sect": "曹洞宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "13",
  "name": "瑠璃寺",
  "kana": "",
  "area": "豊里東",
  "addr": "大畠町東谷田40",
  "lat": 35.336369,
  "lng": 135.227219,
  "approx": true,
  "sect": "曹洞宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "14",
  "name": "楞厳寺",
  "kana": "",
  "area": "豊里東",
  "addr": "舘町楞厳寺6",
  "lat": 35.32375,
  "lng": 135.223572,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "15",
  "name": "惣持院",
  "kana": "",
  "area": "豊里西",
  "addr": "小西町中小路24",
  "lat": 35.332866,
  "lng": 135.207753,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "16",
  "name": "普門院",
  "kana": "",
  "area": "豊里西",
  "addr": "鍛冶屋町定国3",
  "lat": 35.340976,
  "lng": 135.1943,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "17",
  "name": "天王寺",
  "kana": "",
  "area": "豊里西",
  "addr": "小畑町松原116",
  "lat": 35.350265,
  "lng": 135.193541,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "18",
  "name": "心田院",
  "kana": "",
  "area": "綾部",
  "addr": "井倉町館3",
  "lat": 35.304706,
  "lng": 135.246388,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "19",
  "name": "極楽寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "白道路町鎌倉田34",
  "lat": 35.354041,
  "lng": 135.251756,
  "approx": false,
  "sect": "臨済宗東福寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "20",
  "name": "満福寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "西坂町宮床65",
  "lat": 35.370996,
  "lng": 135.19479,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "21",
  "name": "長松寺",
  "kana": "",
  "area": "志賀郷",
  "addr": "坊口町林3",
  "lat": 35.387786,
  "lng": 135.236383,
  "approx": false,
  "sect": "曹洞宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "22",
  "name": "宝満寺",
  "kana": "",
  "area": "志賀郷",
  "addr": "西方町大坊29",
  "lat": 35.384172,
  "lng": 135.209619,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "23",
  "name": "長福寺",
  "kana": "",
  "area": "志賀郷",
  "addr": "向田町",
  "lat": 35.363651,
  "lng": 135.251236,
  "approx": true,
  "sect": "",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "24",
  "name": "慈眼寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "上八田町高柳2",
  "lat": 35.354697,
  "lng": 135.285602,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "25",
  "name": "岩王寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "七百石町寺ノ段1",
  "lat": 35.364469,
  "lng": 135.297416,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "26",
  "name": "安国寺",
  "kana": "",
  "area": "東八田",
  "addr": "安国寺町寺ノ段1",
  "lat": 35.340889,
  "lng": 135.307254,
  "approx": false,
  "sect": "臨済宗東福寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "27",
  "name": "禅徳寺",
  "kana": "",
  "area": "東八田",
  "addr": "上杉町森東8",
  "lat": 35.35472,
  "lng": 135.31678,
  "approx": false,
  "sect": "臨済宗東福寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "28",
  "name": "施福寺",
  "kana": "",
  "area": "東八田",
  "addr": "上杉町寺ノ迫19",
  "lat": 35.357279,
  "lng": 135.341466,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "29",
  "name": "日円寺",
  "kana": "",
  "area": "上林",
  "addr": "井根町寺ノ段34",
  "lat": 35.351055,
  "lng": 135.359849,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "30",
  "name": "善福寺",
  "kana": "",
  "area": "上林",
  "addr": "睦合町大門段65",
  "lat": 35.359077,
  "lng": 135.393048,
  "approx": false,
  "sect": "高野山真言宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "31",
  "name": "上林禅寺",
  "kana": "",
  "area": "上林",
  "addr": "八津合町村中1",
  "lat": 35.366548,
  "lng": 135.409143,
  "approx": false,
  "sect": "臨済宗南禅寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "32",
  "name": "五泉寺",
  "kana": "",
  "area": "上林",
  "addr": "五津合町西巻49",
  "lat": 35.409335,
  "lng": 135.417793,
  "approx": true,
  "sect": "臨済宗南禅寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "33",
  "name": "光明寺",
  "kana": "",
  "area": "上林",
  "addr": "睦寄町君尾1",
  "lat": 35.389699,
  "lng": 135.442221,
  "approx": false,
  "sect": "真言宗醍醐派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B1",
  "name": "妙徳寺",
  "kana": "",
  "area": "物部・西八田",
  "addr": "渕垣町奥ノ谷35の乙",
  "lat": 35.322343,
  "lng": 135.290837,
  "approx": false,
  "sect": "臨済宗妙心寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B2",
  "name": "長福寺",
  "kana": "",
  "area": "豊里東",
  "addr": "栗町",
  "lat": 35.31638,
  "lng": 135.221451,
  "approx": true,
  "sect": "",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B3",
  "name": "雲源寺",
  "kana": "",
  "area": "東八田",
  "addr": "梅迫町中町49",
  "lat": 35.344821,
  "lng": 135.309648,
  "approx": false,
  "sect": "臨済宗東福寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B4",
  "name": "随岸寺",
  "kana": "",
  "area": "中筋・山家",
  "addr": "和木町西浦26",
  "lat": 35.27949,
  "lng": 135.288535,
  "approx": false,
  "sect": "臨済宗東福寺派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B5",
  "name": "高源寺",
  "kana": "",
  "area": "豊里西",
  "addr": "小畑町松原150",
  "lat": 35.350866,
  "lng": 135.194497,
  "approx": false,
  "sect": "曹洞宗",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 },
 {
  "no": "B6",
  "name": "久香寺",
  "kana": "",
  "area": "東八田",
  "addr": "梅迫町正月谷12",
  "lat": 35.346589,
  "lng": 135.309333,
  "approx": false,
  "sect": "真言宗御室派",
  "sango": "",
  "honzon": "",
  "shuji": "",
  "goeika": "",
  "memo": ""
 }
];
